network:
  version: 2
  ethernets:
    ethernet:
      match:
        name: "e*"
      dhcp4: true
      optional: true
      dhcp4-overrides:
        route-metric: 200
  wifis:
    wlan0:
      dhcp4: true
      optional: true
      dhcp4-overrides:
        route-metric: 100
      access-points:
        "SSSA":
          auth:
            key-management: psk
            password: "9dea540b557be2dd2facbdbf74ed2e16e5933b13415498a9a3483a632bffb5c6"
